## https://github.com/kubernetes/ingress-nginx/tree/main/charts/ingress-nginx: in this link below commands available
controller:
  service:
    targetPorts:
      http: http
      https: http
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: nlb
      service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:904827379241:certificate/2f308a9e-e05b-425c-88a6-e1ee15440069
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tls"
      service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
